# Generated by Django 5.2.16 on 2026-08-03 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=250)),
                ('function', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('premise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='assets.premise')),
            ],
            options={
                'ordering': ['premise', 'code'],
                'constraints': [models.UniqueConstraint(fields=('premise', 'code'), name='unique_block_code_per_premise')],
            },
        ),
    ]
