# Generated by Django 5.2.16 on 2026-08-03 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='assets.block')),
            ],
            options={
                'ordering': ['block', 'sequence', 'code'],
                'constraints': [models.UniqueConstraint(fields=('block', 'code'), name='unique_level_code_per_block')],
            },
        ),
    ]
