# Generated by Django 5.2.16 on 2026-08-03 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('function_code', models.CharField(blank=True, max_length=50)),
                ('function_name', models.CharField(blank=True, max_length=200)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_tag', models.CharField(editable=False, max_length=100, unique=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='assets.level')),
            ],
            options={
                'ordering': ['level', 'code'],
                'constraints': [models.UniqueConstraint(fields=('level', 'code'), name='unique_room_code_per_level')],
            },
        ),
    ]
