# Generated by Django 5.2.16 on 2026-08-03 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('component_code', models.CharField(blank=True, max_length=100)),
                ('discipline', models.CharField(choices=[('A', 'Civil and Architecture'), ('E', 'Electrical'), ('M', 'Mechanical'), ('T', 'ICT and ELV'), ('B', 'Biomedical'), ('L', 'Other')], max_length=1)),
                ('system', models.CharField(max_length=250)),
                ('subsystem', models.CharField(blank=True, max_length=250)),
                ('brand', models.CharField(blank=True, max_length=150)),
                ('model', models.CharField(blank=True, max_length=150)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('returned', 'Returned for Correction'), ('verified', 'Verified'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='assets.room')),
            ],
            options={
                'ordering': ['component_id'],
            },
        ),
    ]
