# Generated by Django 5.2.16 on 2026-08-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='public_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
