# Generated by Django 5.2.16 on 2026-08-03 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_component_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
