# Generated by Django 5.2.16 on 2026-08-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_component_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='security_level',
            field=models.CharField(choices=[('public', 'Public'), ('staff', 'Staff Only'), ('restricted', 'Restricted')], default='staff', max_length=20),
        ),
        migrations.AddField(
            model_name='block',
            name='structure_type',
            field=models.CharField(choices=[('building', 'Building Block'), ('external', 'External Structure')], default='building', max_length=20),
        ),
    ]
