# Generated by Django 5.2.16 on 2026-08-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_block_security_level_block_structure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='security_level',
            field=models.CharField(choices=[('public', 'Public'), ('staff', 'Staff Only'), ('restricted', 'Restricted')], default='staff', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='space_type',
            field=models.CharField(choices=[('room', 'Enclosed Room'), ('open_area', 'Open Area')], default='room', max_length=20),
        ),
    ]
