# Generated by Django 5.2.16 on 2026-08-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_room_security_level_room_space_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='security_level',
            field=models.CharField(choices=[('public', 'Public'), ('staff', 'Staff Only'), ('restricted', 'Restricted')], default='staff', max_length=20),
        ),
    ]
