# Generated by Django 5.2.16 on 2026-08-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_component_security_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='premise',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='premise',
            name='installation_photo',
            field=models.ImageField(blank=True, null=True, upload_to='premise_labels/'),
        ),
        migrations.AddField(
            model_name='premise',
            name='jkr_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='premise',
            name='label_material',
            field=models.CharField(default='Stainless Steel 304 Hairline Finish 1.5mm', max_length=200),
        ),
        migrations.AddField(
            model_name='premise',
            name='label_size',
            field=models.CharField(default='600mm x 400mm', max_length=100),
        ),
        migrations.AddField(
            model_name='premise',
            name='label_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('prepared', 'Prepared'), ('installed', 'Installed'), ('verified', 'Verified')], default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='premise',
            name='owner_agency',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='premise',
            name='qr_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='premise',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='premise',
            name='dpa_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
