# Generated by Django 5.2.16 on 2026-08-05 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_premise_installation_date_premise_installation_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', models.CharField(choices=[('dpa', 'DPA Label'), ('block', 'DAK Block / External Structure'), ('level', 'DAK Level'), ('room', 'DAK Room'), ('component', 'DAK Component')], max_length=30)),
                ('label_code', models.CharField(max_length=100, unique=True)),
                ('qr_code', models.CharField(blank=True, max_length=500)),
                ('label_size', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('printed', 'Printed'), ('installed', 'Installed'), ('verified', 'Verified')], default='draft', max_length=30)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('installer', models.CharField(blank=True, max_length=150)),
                ('installation_photo', models.ImageField(blank=True, null=True, upload_to='label_evidence/')),
                ('verified_by', models.CharField(blank=True, max_length=150)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='assets.block')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='assets.component')),
                ('premise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='assets.premise')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='assets.room')),
            ],
        ),
    ]
