# Generated by Django 5.2.16 on 2026-08-05 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_assetlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_id', models.CharField(max_length=100, unique=True)),
                ('qr_type', models.CharField(choices=[('premise', 'Premise QR'), ('block', 'Block QR'), ('room', 'Room QR'), ('component', 'Component QR')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='assets.block')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='assets.component')),
                ('premise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='assets.premise')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='assets.room')),
            ],
        ),
    ]
