# Generated by Django 5.2.16 on 2026-08-05 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_dynamicqrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicqrcode',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='assets.level'),
        ),
        migrations.AlterField(
            model_name='dynamicqrcode',
            name='qr_type',
            field=models.CharField(choices=[('premise', 'Premise QR'), ('block', 'Block QR'), ('level', 'Level QR'), ('room', 'Room QR'), ('component', 'Component QR')], max_length=30),
        ),
    ]
