# Generated by Django 5.2.16 on 2026-08-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_dynamicqrcode_level_alter_dynamicqrcode_qr_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicqrcode',
            name='scan_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
