# Generated by Django 5.2.16 on 2026-08-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_dynamicqrcode_scan_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicqrcode',
            name='public_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
