# Generated by Django 5.2.16 on 2026-08-06 01:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_dynamicqrcode_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicqrcode',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
