# Generated by Django 5.2.16 on 2026-08-06 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_alter_dynamicqrcode_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicqrcode',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicqrcode',
            name='replaced_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='assets.dynamicqrcode'),
        ),
        migrations.AddField(
            model_name='dynamicqrcode',
            name='replacement_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
