# Generated by Django 5.2.16 on 2026-08-06 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_dynamicqrcode_deactivated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('drawing_type', models.CharField(choices=[('architectural', 'Architectural'), ('structural', 'Structural'), ('civil', 'Civil'), ('mechanical', 'Mechanical'), ('electrical', 'Electrical'), ('as_built', 'As-Built'), ('other', 'Other')], max_length=30)),
                ('revision', models.CharField(default='0', max_length=20)),
                ('drawing_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='drawings/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('current', 'Current'), ('superseded', 'Superseded'), ('archived', 'Archived')], default='current', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawings', to='assets.block')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawings', to='assets.component')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawings', to='assets.level')),
                ('premise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='assets.premise')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawings', to='assets.room')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_drawings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['drawing_number', '-revision'],
                'constraints': [models.UniqueConstraint(fields=('drawing_number', 'revision'), name='unique_drawing_revision')],
            },
        ),
    ]
