# Generated by Django 5.2.16 on 2026-08-06 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_drawing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('manual', 'Operation and Maintenance Manual'), ('warranty', 'Warranty Document'), ('certificate', 'Certificate'), ('inspection', 'Inspection Report'), ('maintenance', 'Maintenance Report'), ('handover', 'Handover Document'), ('contract', 'Contract Document'), ('other', 'Other')], max_length=30)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('current', 'Current'), ('expired', 'Expired'), ('archived', 'Archived')], default='current', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='assets.block')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='assets.component')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='assets.level')),
                ('premise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assets.premise')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='assets.room')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_asset_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_number'],
            },
        ),
    ]
