# Generated by Django 5.2.16 on 2026-08-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_assetdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomFunctionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room Function Code',
                'verbose_name_plural': 'Room Function Codes',
                'ordering': ['code'],
            },
        ),
    ]
