# Generated by Django 5.2.16 on 2026-08-07 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_roomfunctioncode'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='assets.roomfunctioncode'),
        ),
    ]
