# Generated by Django 5.2.16 on 2026-08-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_room_room_function'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomfunctioncode',
            options={'ordering': ['space_type_code', 'category_code', 'code'], 'verbose_name': 'Room Function Code', 'verbose_name_plural': 'Room Function Codes'},
        ),
        migrations.AddField(
            model_name='roomfunctioncode',
            name='category_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='roomfunctioncode',
            name='space_type_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='roomfunctioncode',
            name='space_type_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='roomfunctioncode',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
