# Generated by Django 5.2.16 on 2026-08-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_excelimportbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelimportbatch',
            name='import_sheet',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
