# Generated by Django 5.2.16 on 2026-08-07 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_excelimportbatch_import_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelimportbatch',
            name='premise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excel_import_batches', to='assets.premise'),
        ),
    ]
