# Generated by Django 5.2.16 on 2026-08-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_excelimportbatch_premise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelimportbatch',
            name='import_type',
            field=models.CharField(choices=[('full_da6', 'Full DA6 Bulk Import'), ('rooms', 'Rooms & Open Areas'), ('components', 'Asset Components')], default='full_da6', max_length=20),
        ),
    ]
