# Generated by Django 5.2.16 on 2026-08-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0029_maintenancerequest_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_tag',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
