# Generated by Django 5.2.16 on 2026-08-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0030_alter_room_room_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={},
        ),
        migrations.AlterField(
            model_name='component',
            name='component_id',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(fields=('room', 'component_id'), name='unique_component_per_room'),
        ),
    ]
