# Generated by Django 5.2.16 on 2026-08-14 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0031_alter_component_options_alter_component_component_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dynamicqrcode',
            name='qr_id',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True),
        ),
    ]
