from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "assets"

urlpatterns = [
    path(
        "",
        views.dashboard,
        name="dashboard",
    ),
    path(
        "premises/",
        views.premise_list,
        name="premise_list",
    ),
    path(
        "premises/add/",
        views.premise_create,
        name="premise_create",
    ),
    path(
        "premises/<int:premise_id>/edit/",
        views.premise_update,
        name="premise_update",
    ),
    path(
    "premises/<int:premise_id>/delete/",
        views.premise_delete,
        name="premise_delete",
    ),
    path(
        "premises/<int:premise_id>/qr/",
        views.premise_qr_code,
        name="premise_qr_code",
    ),
    path(
        "blocks/",
        views.block_list,
        name="block_list",
    ),
    path(
        "blocks/add/",
        views.block_create,
        name="block_create",
    ),
    path(
        "blocks/<int:block_id>/edit/",
        views.block_update,
        name="block_update",
    ),
    path(
        "blocks/<int:block_id>/qr/",
        views.block_qr_code,
        name="block_qr_code",
    ),
    path(
        "levels/",
        views.level_list,
        name="level_list",
    ),
    path(
        "levels/add/",
        views.level_create,
        name="level_create",
    ),
    path(
        "levels/<int:level_id>/edit/",
        views.level_update,
        name="level_update",
    ),
    path(
        "levels/<int:level_id>/delete/",
        views.level_delete,
        name="level_delete",
    ),
    path(
        "levels/<int:level_id>/qr/",
        views.level_qr_code,
        name="level_qr_code",
    ),
    path(
        "rooms/",
        views.room_list,
        name="room_list",
    ),
    path(
        "rooms/add/",
        views.room_create,
        name="room_create",
    ),
    path(
        "rooms/<int:room_id>/edit/",
        views.room_edit,
        name="room_edit",
    ),
    path(
        "rooms/<int:room_id>/delete/",
        views.room_delete,
        name="room_delete",
    ),
    path(
        "rooms/<int:room_id>/qr/",
        views.room_qr_code,
        name="room_qr_code",
    ),
    path(
        "components/",
        views.component_list,
        name="component_list",
    ),
    path(
        "components/add/",
        views.component_create,
        name="component_create",
    ),
    path(
        "components/<int:component_id>/edit/",
        views.component_update,
        name="component_update",
    ),
    path(
        "components/<int:component_id>/delete/",
        views.component_delete,
        name="component_delete",
    ),
    path(
        "labels/",
        views.label_list,
        name="label_list",
    ),
    path(
        "scan/<uuid:public_id>/",
        views.qr_scan,
        name="qr_scan",
        ),
    path(
        "scan/<str:qr_id>/",
        views.qr_scan_legacy,
        name="qr_scan_legacy",
    ),
    path(
        "qr-codes/",
        views.qr_code_list,
        name="qr_code_list",
    ),
    path(
        "qr-codes/add/",
        views.qr_code_create,
        name="qr_code_create",
    ),
    path(
        "qr-codes/<str:qr_id>/edit/",
        views.qr_code_edit,
        name="qr_code_edit",
    ),
    path(
        "qr-codes/<str:qr_id>/replace/",
        views.qr_code_replace,
        name="qr_code_replace",
    ),
    path(
        "qr-codes/<str:qr_id>/image/",
        views.dynamic_qr_image,
        name="dynamic_qr_image",
    ),
    path(
        "qr-codes/<str:qr_id>/download/",
        views.dynamic_qr_download,
        name="dynamic_qr_download",
    ),
    path(
        "qr-codes/<str:qr_id>/label/",
        views.qr_label_preview,
        name="qr_label_preview",
    ),
    path(
        "drawings/",
        views.drawing_list,
        name="drawing_list",
    ),
    path(
        "drawings/add/",
        views.drawing_create,
        name="drawing_create",
    ),
    path(
        "drawings/<int:drawing_id>/edit/",
        views.drawing_edit,
        name="drawing_edit",
    ),
    path(
        "drawings/<int:drawing_id>/archive/",
        views.drawing_archive,
        name="drawing_archive",
    ),
    path(
        "drawings/<int:drawing_id>/file/",
        views.drawing_download,
        name="drawing_download",
    ),
    path(
        "drawings/<int:drawing_id>/new-revision/",
        views.drawing_new_revision,
        name="drawing_new_revision",
    ),
    # Asset Documents
    path(
        "documents/",
        views.asset_document_list,
        name="asset_document_list",
    ),
    path(
        "documents/add/",
        views.asset_document_create,
        name="asset_document_create",
    ),
    path(
        "documents/<int:document_id>/edit/",
        views.asset_document_edit,
        name="asset_document_edit",
    ),
    path(
        "documents/<int:document_id>/archive/",
        views.asset_document_archive,
        name="asset_document_archive",
    ),
    path(
        "documents/<int:document_id>/file/",
        views.asset_document_download,
        name="asset_document_download",
    ),
    # Excel Import
    path(
        "imports/add/",
        views.excel_import_create,
        name="excel_import_create",
    ),

    path(
        "imports/<int:batch_id>/",
        views.excel_import_detail,
        name="excel_import_detail",
    ),
    path(
        "imports/<int:batch_id>/execute/",
        views.excel_import_execute,
        name="excel_import_execute",
    ),
    path(
        "maintenance/",
        views.maintenance_dashboard,
        name="maintenance_dashboard",
    ),
    path(
        "maintenance/requests/",
        views.maintenance_request_list,
        name="maintenance_request_list",
    ),
    path(
        "maintenance/requests/<int:request_id>/",
        views.maintenance_request_detail,
        name="maintenance_request_detail",
    ),
    path(
        "maintenance/requests/<int:request_id>/assign/",
        views.maintenance_request_assign,
        name="maintenance_request_assign",
    ),
    path(
        "maintenance/requests/<int:request_id>/start/",
        views.maintenance_request_start,
        name="maintenance_request_start",
    ),
    path(
        "maintenance/requests/<int:request_id>/complete/",
        views.maintenance_request_complete,
        name="maintenance_request_complete",
    ),
    path(
        "maintenance/requests/<int:request_id>/close/",
        views.maintenance_request_close,
        name="maintenance_request_close",
    ),
    path(
        "maintenance/requests/add/",
        views.maintenance_request_create,
        name="maintenance_request_create",
    ),
    path(
        "maintenance/ajax/blocks/",
        views.maintenance_load_blocks,
        name="maintenance_load_blocks",
    ),
    path(
        "maintenance/ajax/levels/",
        views.maintenance_load_levels,
        name="maintenance_load_levels",
    ),
    path(
        "maintenance/ajax/rooms/",
        views.maintenance_load_rooms,
        name="maintenance_load_rooms",
    ),
    path(
        "maintenance/ajax/components/",
        views.maintenance_load_components,
        name="maintenance_load_components",
    ),
    path(
        "maintenance/report/<uuid:public_id>/",
        views.maintenance_report_from_qr,
        name="maintenance_report_from_qr",
    ),
    path(
        "reports/",
        views.reports_dashboard,
        name="reports_dashboard",
    ),
    path(
        "reports/assets/",
        views.asset_report,
        name="asset_report",
    ),
    path(
        "reports/assets/pdf/",
        views.asset_report_pdf,
        name="asset_report_pdf",
    ),
    path(
        "reports/maintenance/",
        views.maintenance_report,
        name="maintenance_report",
    ),
    path(
        "reports/maintenance/pdf/",
        views.maintenance_report_pdf,
        name="maintenance_report_pdf",
    ),
    path(
        "reports/handover/",
        views.handover_report,
        name="handover_report",
    ),
    path(
        "reports/handover/pdf/",
        views.handover_report_pdf,
        name="handover_report_pdf",
    ),
    path(
        "component/<uuid:public_id>/",
        views.component_public_detail,
        name="component_public_detail",
    ),
    path(
        "component/<uuid:public_id>/qr/",
        views.component_qr_code,
        name="component_qr_code",
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
